@startuml add catch
actor "Användare" as User

usecase "Lägg till ny fångst" as UC0
usecase "Vilken art" as UC1
usecase "Skriv in vikt" as UC2
usecase "Skriv in längd" as UC3
usecase "Fångstplats" as UC4
usecase "Välj bete" as UC5
usecase "Anteckningar" as UC6
usecase "Lägg till photo" as UC7
usecase "Använd GPS-position" as UC8
usecase "Spara fångst" as UC9

User --> UC0
UC0 --> UC1 : includes
UC0 --> UC2 : includes
UC0 --> UC3 : includes
UC0 --> UC4 : includes
UC0 --> UC5 : includes
UC0 --> UC6 : includes
UC0 --> UC7 : extends
UC0 --> UC8 : extends
UC0 --> UC9 : includes
@enduml